#!/bin/sh

# 保留 K3 上游默认交换机/VLAN 布局，只补充 USB 共享网络接口。
uci -q set network.lan.ipaddr='10.10.10.1'
uci -q set network.lan.netmask='255.255.255.0'

uci -q set network.usbv4='interface'
uci -q set network.usbv4.proto='dhcp'
uci -q delete network.usbv4.device
uci -q delete network.usbv4.ifname

uci -q set network.usbv6='interface'
uci -q set network.usbv6.proto='dhcpv6'
uci -q delete network.usbv6.device
uci -q delete network.usbv6.ifname
uci -q set network.usbv6.reqaddress='try'
uci -q set network.usbv6.reqprefix='auto'

wan_zone="$(uci show firewall | sed -n "s/^firewall\.\([^=]*\)\.name='wan'$/\1/p" | head -n1)"
if [ -n "$wan_zone" ]; then
	current_networks="$(uci -q get firewall.${wan_zone}.network)"
	case " $current_networks " in
		*" usbv4 "*) ;;
		*) uci add_list firewall.${wan_zone}.network='usbv4' ;;
	esac
	case " $current_networks " in
		*" usbv6 "*) ;;
		*) uci add_list firewall.${wan_zone}.network='usbv6' ;;
	esac
fi

uci commit network
uci commit firewall

exit 0
